### ISSUE TITLE
mutex and rwlock singletons

### ISSUE THREAD

**Issue by haraldh** [4lDO2/spinning-rs#4]
Are you interested in adding a macro to implement mutex and rwlock singletons?

See: https://github.com/haraldh/enarx/blob/sev_paging/enarx-keep-sev-shim/src/singleton.rs

Example usage:
https://github.com/haraldh/enarx/blob/sev_paging/enarx-keep-sev-shim/src/frame_allocator.rs#L21-L23
https://github.com/haraldh/enarx/blob/sev_paging/enarx-keep-sev-shim/src/paging.rs#L12-L14
https://github.com/haraldh/enarx/blob/sev_paging/enarx-keep-sev-shim/src/hostcall.rs#L45-L47

**Comment by 4lDO2** [comment]
@haraldh Yes, that seems like a good idea. I unfortunately don't have time right now to implement this myself, but I'd happily accept a PR.

**Comment by haraldh** [comment]
@4lDO2 ok, cool! I'll play around with it a longer time and test it in production. I'll file a PR, when I am ready to publish.
